"""empty message

Revision ID: 32b02e0b5885
Revises: None
Create Date: 2015-10-19 16:06:08.335861

"""

# revision identifiers, used by Alembic.
revision = '32b02e0b5885'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commitment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salad_id', sa.Integer(), nullable=True),
    sa.Column('person', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=10), nullable=True),
    sa.Column('ingredient', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['category.id'], ),
    sa.ForeignKeyConstraint(['salad_id'], ['salad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commitment')
    op.drop_table('salad')
    op.drop_table('category')
    ### end Alembic commands ###
